name: pipeline
on:
  push:
    branches:
      - "main"

permissions:
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Read versions and set tags
        id: set-tags
        run: |
          # Initialize the TAGS variable with default tags
          TAGS="jtwebman/pg-docker-backup:latest\\njtwebman/pg-docker-backup:${{ github.sha }}"

          # Read each version from the VERSIONS file and append it as a tag
          while IFS= read -r version; do
            if [ -n "$version" ]; then
              TAGS="$TAGS\\njtwebman/pg-docker-backup:$version"
            fi
          done < VERSIONS

          # Save the tags as a multi-line string output for the next step
          echo "tags=$TAGS" >> $GITHUB_ENV

      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.tags }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: jtwebman/pg-docker-backup
          short-description: ${{ github.event.repository.description }}
