name: pipeline
on:
  push:
    branches:
      - "main"

permissions:
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            jtwebman/pg-docker-backup:latest
            jtwebman/pg-docker-backup:${{ github.sha }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: jtwebman/pg-docker-backup
